name: Build & test image

on:
  workflow_call:
    inputs:
      build-args:
        required: false
        type: string
      image-namespace:
        required: true
        type: string
      image-repo:
        required: true
        type: string
      no-cache-filter:
        required: false
        type: string

jobs:
  build:
    name: Build & test image
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Debug on runner (When re-run with "Enable debug logging" checked)
        if: runner.debug
        uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 # v3.23
        with:
          detached: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Build and export locally to Docker
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          load: true
          tags: ${{ inputs.image-namespace }}/${{ inputs.image-repo }}:local-test
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache-filters: ${{ inputs.no-cache-filter }}
      - name: Install Test Kitchen
        uses: ruby/setup-ruby@dffb23f65a78bba8db45d387d5ea1bbd6be3ef18 # v1.293.0
        with:
          bundler-cache: true
          ruby-version: '3.1'
      - name: Run Test Kitchen
        run: bundle exec kitchen test
