name: Build & test image

on:
  workflow_call:
    inputs:
      build-args:
        required: false
        type: string
      image-namespace:
        required: true
        type: string
      image-repo:
        required: true
        type: string
      no-cache-filter:
        required: false
        type: string

jobs:
  build:
    name: Build & test image
    runs-on: ubuntu-26.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Debug on runner (When re-run with "Enable debug logging" checked)
        if: runner.debug
        uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3.24
        with:
          detached: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - name: Build and export locally to Docker
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          context: .
          load: true
          tags: ${{ inputs.image-namespace }}/${{ inputs.image-repo }}:local-test
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache-filters: ${{ inputs.no-cache-filter }}
      - name: Install Test Kitchen
        uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
        with:
          bundler-cache: true
          ruby-version: '3.4'
      - name: Run Test Kitchen
        run: bundle exec kitchen test
