name: Build & test image

on:
  workflow_call:
    inputs:
      build-args:
        required: false
        type: string
      image-namespace:
        required: true
        type: string
      image-repo:
        required: true
        type: string
      no-cache-filter:
        required: false
        type: string

jobs:
  build:
    name: Build & test image
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Debug on runner (When re-run with "Enable debug logging" checked)
        if: runner.debug
        uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3.24
        with:
          detached: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - name: Build and export locally to Docker
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          load: true
          tags: ${{ inputs.image-namespace }}/${{ inputs.image-repo }}:local-test
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache-filters: ${{ inputs.no-cache-filter }}
      - name: Install Test Kitchen
        uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          bundler-cache: true
          ruby-version: '3.1'
      - name: Run Test Kitchen
        run: bundle exec kitchen test
